#!/usr/bin/env bash

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function auth () {

  clear
  echo
  echo

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan ajp-auth "
  echo -e $white"    [$okegreen"02"$white]$cyan creds-summary  "
  echo -e $white"    [$okegreen"03"$white]$cyan domcon-cmd "
  echo -e $white"    [$okegreen"04"$white]$cyan domino-enum-users  "
  echo -e $white"    [$okegreen"05"$white]$cyan ftp-anon "
  echo -e $white"    [$okegreen"06"$white]$cyan http-auth  "
  echo -e $white"    [$okegreen"07"$white]$cyan http-barracuda-dir-traversal "
  echo -e $white"    [$okegreen"08"$white]$cyan http-config-backup "
  echo -e $white"    [$okegreen"09"$white]$cyan http-default-accounts  "
  echo -e $white"    [$okegreen"10"$white]$cyan http-domino-enum-passwords "
  echo -e $white"    [$okegreen"11"$white]$cyan http-method-tamper "
  echo -e $white"    [$okegreen"12"$white]$cyan http-userdir-enum  "
  echo -e $white"    [$okegreen"13"$white]$cyan http-vuln-cve2010-0738 "
  echo -e $white"    [$okegreen"14"$white]$cyan http-wordpress-users "
  echo -e $white"    [$okegreen"15"$white]$cyan informix-query "
  echo -e $white"    [$okegreen"16"$white]$cyan informix-tables  "
  echo -e $white"    [$okegreen"17"$white]$cyan krb5-enum-users  "
  echo -e $white"    [$okegreen"18"$white]$cyan ms-sql-dump-hashes"
  echo -e $white"    [$okegreen"19"$white]$cyan ms-sql-empty-password  "
  echo -e $white"    [$okegreen"20"$white]$cyan ms-sql-hasdbaccess "
  echo -e $white"    [$okegreen"21"$white]$cyan mysql-dump-hashes  "
  echo -e $white"    [$okegreen"22"$white]$cyan mysql-empty-password "
  echo -e $white"    [$okegreen"23"$white]$cyan mysql-query  "
  echo -e $white"    [$okegreen"24"$white]$cyan mysql-users  "
  echo -e $white"    [$okegreen"25"$white]$cyan ncp-enum-users "
  echo -e $white"    [$okegreen"26"$white]$cyan netbus-auth-bypass "
  echo -e $white"    [$okegreen"27"$white]$cyan oracle-enum-users  "
  echo -e $white"    [$okegreen"28"$white]$cyan realvnc-auth-bypass  "
  echo -e $white"    [$okegreen"29"$white]$cyan sip-enum-users "
  echo -e $white"    [$okegreen"30"$white]$cyan smb-enum-users "
  echo -e $white"    [$okegreen"31"$white]$cyan smtp-enum-users  "
  echo -e $white"    [$okegreen"32"$white]$cyan snmp-win32-users "
  echo -e $white"    [$okegreen"33"$white]$cyan x11-access "
  echo -e $white"    [$okegreen"34"$white]$cyan Back "
  echo -e " "

  echo -n -e $red'  \033[4mScreetsec@nse-auth:\033[0m>> '; tput sgr0 #insert your choice
  read win

  if [[ $win -eq 1 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 8009 $ip --script ajp-auth [--script-args ajp-auth.path=/login] &

  elif [[ $win -eq 2 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV -sC $ip &

  elif [[ $win -eq 3 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " What is your cmd user: " ; tput sgr0
    read user
    echo -ne $okegreen " What is your cmd pass: " ; tput sgr0
    read pass
    $xterm -p 2050 $ip --script domcon-cmd --script-args domcon-cmd.cmd="show server" domcon-cmd.user="$user",domcon-cmd.pass="$pass" &

  elif [[ $win -eq 4 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script domino-enum-users -p 1352 $ip &

  elif [[ $win -eq 5 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV -sC $ip &

  elif [[ $win -eq 6 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script http-auth [--script-args http-auth.path=/login] -p80 $ip &

  elif [[ $win -eq 7 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " What is your Port Target " ; tput sgr0
    read port
    $xterm --script http-barracuda-dir-traversal --script-args http-max-cache-size=5000000 -p $port $ip &

  elif [[ $win -eq 8 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=http-config-backup $ip &

  elif [[ $win -eq 9 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 80 --script http-default-accounts $ip &

  elif [[ $win -eq 10 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " What the username: " ; tput sgr0
    read user
    echo -ne $okegreen " What the password: " ; tput sgr0
    read pass
    $xterm  --script domino-enum-passwords -p 80 $ip --script-args domino-enum-passwords.username=$user,domino-enum-passwords.password=$pass &

  elif [[ $win -eq 11 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm p80 --script http-method-tamper --script-args 'http-method-tamper.paths={/protected/db.php,/protected/index.php}' $ip &

  elif [[ $win -eq 12 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=http-userdir-enum $ip  &

  elif [[ $win -eq 13 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=http-vuln-cve2010-0738 --script-args 'http-vuln-cve2010-0738.paths={/path1/,/path2/}' $ip &

  elif [[ $win -eq 14 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script http-wordpress-users --script-args limit=50 $ip &

  elif [[ $win -eq 15 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " The username used for authentication: " ; tput sgr0
    read user
    echo -ne $okegreen " The password used for authentication : " ; tput sgr0
    read pass
    $xterm -p 9088 $ip --script informix-query --script-args informix-query.username=$user,informix-query.password=$pass &

  elif [[ $win -eq 16 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " The username used for authentication: " ; tput sgr0
    read user
    echo -ne $okegreen " The password used for authentication : " ; tput sgr0
    read pass
    $xterm -p 9088 $ip --script informix-tables --script-args informix-tables.username=$user,informix-tables.password=$pass &

  elif [[ $win -eq 17 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 88 $ip --script krb5-enum-users --script-args krb5-enum-users.realm='test' &

  elif [[ $win -eq 18 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 1433 $ip --script ms-sql-dump-hashes &

  elif [[ $win -eq 19 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " What is your Port Target or Host: " ; tput sgr0
    read port
    $xterm -p $port --script ms-sql-empty-password --script-args mssql.instance-all $ip &

  elif [[ $win -eq 20 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " The username used for authentication: " ; tput sgr0
    read user
    echo -ne $okegreen " The password used for authentication : " ; tput sgr0
    read pass
    $xterm -p 1433 --script ms-sql-hasdbaccess --script-args mssql.username=$user,mssql.password=$pass $ip &

  elif [[ $win -eq 21 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " The username to use to connect to the server " ; tput sgr0
    read user
    echo -ne $okegreen " The password to use to connect to the server: " ; tput sgr0
    read pass
    $xterm -p 3306 $ip --script mysql-dump-hashes --script-args="username=$user,password=$pass" &

  elif [[ $win -eq 22 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=mysql-empty-password $ip &

  elif [[ $win -eq 23 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " The username to use to connect to the server (Optional):" ; tput sgr0
    read user
    echo -ne $okegreen " The password to use to connect to the server (Optional): " ; tput sgr0
    read pass
    echo -ne $okegreen " The query for which to return the results " ; tput sgr0
    read query
    $xterm -p 3306 $ip --script mysql-query --script-args="query="$query"[,username=$username,password=$pass]" &
  
  elif [[ $win -eq 24 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=mysql-users $ip &

  elif [[ $win -eq 25 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=ncp-enum-users $ip &

  elif [[ $win -eq 26 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 12345 --script netbus-auth-bypass $ip &

  elif [[ $win -eq 27 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script oracle-enum-users --script-args oracle-enum-users.sid=ORCL,userdb=orausers.txt -p 1521-1560 $ip &

  elif [[ $win -eq 28 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV -sC $ip &

  elif [[ $win -eq 29 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=sip-enum-users -sU -p 5060 $ip &

  elif [[ $win -eq 30 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -script smb-enum-users.nse -p 445 $ip &

  elif [[ $win -eq 31 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script smtp-enum-users.nse [--script-args smtp-enum-users.methods={EXPN,...},...] -p 25,465,587 $ip &

  elif [[ $win -eq 32 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sU -p 161 --script=snmp-win32-users $ip &

  elif [[ $win -eq 33 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --sV -sC $ip &

  elif [[ $win -eq 34 ]] ; then

    nse

  else

    echo ""
    echo -e $okegreen " Incorrect Number"

  fi

  echo ""
  echo ""
  echo -n -e $red " Back to Last Menu? ( Yes / No ) :"
  read back

  if [ $back != 'n' ] && \
     [ $back != 'N' ] && \
     [ $back != 'no' ] && \
     [ $back != 'No' ] ; then

    clear
    menu

  elif [ $back != 'y' ] && \
       [ $back != 'Y' ] && \
       [ $back != 'yes' ] && \
       [ $back != 'Yes' ] ; then

    auth

  else

    clear
    auth

  fi

}
