#!/usr/bin/env bash

################################################
# NSE SCRIPT FOR BRUTEFORCE
################################################

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed leading and trailing whitespaces
#   - added smart tabs
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
#   - correcting indentation (transparent code)
function brutense() {

  clear
  echo "                                                   ";

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white "    [$okegreen"01"$white]$cyan  afp-brute  "
  echo -e $white "    [$okegreen"02"$white]$cyan  ajp-brute "
  echo -e $white "    [$okegreen"03"$white]$cyan  backorifice-brute  "
  echo -e $white "    [$okegreen"04"$white]$cyan  cassandra-brute "
  echo -e $white "    [$okegreen"05"$white]$cyan  cics-enum "
  echo -e $white "    [$okegreen"06"$white]$cyan  cics-user-enum "
  echo -e $white "    [$okegreen"07"$white]$cyan  citrix-brute-xml"
  echo -e $white "    [$okegreen"08"$white]$cyan  cvs-brute  "
  echo -e $white "    [$okegreen"09"$white]$cyan  cvs-brute-repository "
  echo -e $white "    [$okegreen"10"$white]$cyan  domcon-brute  "
  echo -e $white "    [$okegreen"11"$white]$cyan  dpap-enum  "
  echo -e $white "    [$okegreen"12"$white]$cyan  drda-brute "
  echo -e $white "    [$okegreen"13"$white]$cyan  ftp-brute  "
  echo -e $white "    [$okegreen"14"$white]$cyan  http-from-brute "
  echo -e $white "    [$okegreen"15"$white]$cyan  http-iis-short-name-brute "
  echo -e $white "    [$okegreen"16"$white]$cyan  http-brute "
  echo -e $white "    [$okegreen"17"$white]$cyan  http-joomla-brute  "
  echo -e $white "    [$okegreen"18"$white]$cyan  http-proxy-brute "
  echo -e $white "    [$okegreen"19"$white]$cyan  http-wordpress-brute "
  echo -e $white "    [$okegreen"20"$white]$cyan  iax2-brute "
  echo -e $white "    [$okegreen"21"$white]$cyan  informix-brute "
  echo -e $white "    [$okegreen"22"$white]$cyan  ipmi-brute "
  echo -e $white "    [$okegreen"23"$white]$cyan  irc-brute "
  echo -e $white "    [$okegreen"24"$white]$cyan  irc-sasl-brute "
  echo -e $white "    [$okegreen"25"$white]$cyan  iscsi-brute "
  echo -e $white "    [$okegreen"26"$white]$cyan  ldap-brute "
  echo -e $white "    [$okegreen"27"$white]$cyan  imap-brute "
  echo -e $white "    [$okegreen"28"$white]$cyan  membase-brute "
  echo -e $white "    [$okegreen"29"$white]$cyan  mmouse-brute "
  echo -e $white "    [$okegreen"30"$white]$cyan  mongodb-brute "
  echo -e $white "    [$okegreen"31"$white]$cyan  ms-sql-brute "
  echo -e $white "    [$okegreen"32"$white]$cyan  mysql-brute "
  echo -e $white "    [$okegreen"33"$white]$cyan  mysql-enum "
  echo -e $white "    [$okegreen"34"$white]$cyan  mongodb-brute"
  echo -e $white "    [$okegreen"35"$white]$cyan  metasploit-msgrpc-brute "
  echo -e $white "    [$okegreen"36"$white]$cyan  metasploit-xmlrpc-brute  "
  echo -e $white "    [$okegreen"37"$white]$cyan  mikrotik-routeros-brute "
  echo -e $white "    [$okegreen"38"$white]$cyan  nessus-xmlrpc-brute "
  echo -e $white "    [$okegreen"39"$white]$cyan  netbus-brute "
  echo -e $white "    [$okegreen"40"$white]$cyan  nexpose-brute "
  echo -e $white "    [$okegreen"41"$white]$cyan  nje-node-brute "
  echo -e $white "    [$okegreen"42"$white]$cyan  nje-pass-brute "
  echo -e $white "    [$okegreen"43"$white]$cyan  nping-brute "
  echo -e $white "    [$okegreen"44"$white]$cyan  nessus-brute "
  echo -e $white "    [$okegreen"45"$white]$cyan  omp2-brute "
  echo -e $white "    [$okegreen"46"$white]$cyan  openvas-otp-brute "
  echo -e $white "    [$okegreen"47"$white]$cyan  oracle-brute "
  echo -e $white "    [$okegreen"48"$white]$cyan  oracle-brute-stealth "
  echo -e $white "    [$okegreen"49"$white]$cyan  oracle-sid-brute "
  echo -e $white "    [$okegreen"50"$white]$cyan  pcanywhere-brute "
  echo -e $white "    [$okegreen"51"$white]$cyan  pgsql-brute "
  echo -e $white "    [$okegreen"52"$white]$cyan  pop3-brute "
  echo -e $white "    [$okegreen"53"$white]$cyan  redis-brute "
  echo -e $white "    [$okegreen"54"$white]$cyan  rexec-brute "
  echo -e $white "    [$okegreen"55"$white]$cyan  rlogin-brute "
  echo -e $white "    [$okegreen"56"$white]$cyan  rpcap-brute "
  echo -e $white "    [$okegreen"57"$white]$cyan  rsync-brute "
  echo -e $white "    [$okegreen"58"$white]$cyan  rtsp-url-brute "
  echo -e $white "    [$okegreen"59"$white]$cyan  sip-brute "
  echo -e $white "    [$okegreen"60"$white]$cyan  socks-brute "
  echo -e $white "    [$okegreen"61"$white]$cyan  svn-brute "
  echo -e $white "    [$okegreen"62"$white]$cyan  tso-enum "
  echo -e $white "    [$okegreen"63"$white]$cyan  smb-brute "
  echo -e $white "    [$okegreen"64"$white]$cyan  smtp-brute  "
  echo -e $white "    [$okegreen"65"$white]$cyan  snmp-brute "
  echo -e $white "    [$okegreen"66"$white]$cyan  telnet-brute "
  echo -e $white "    [$okegreen"67"$white]$cyan  vtam-enum "
  echo -e $white "    [$okegreen"68"$white]$cyan  vmauthd-brute "
  echo -e $white "    [$okegreen"69"$white]$cyan  vnc-brute"
  echo -e $white "    [$okegreen"70"$white]$cyan  xmpp-brute "
  echo -e $white "    [$okegreen"71"$white]$cyan  Back "
  echo -e " "

  echo -n -e $red'  \033[4mScreetsec@nse-brute:\033[0m>> '; tput sgr0 #insert your choice
  read Brute

  if [[ $Brute -eq 1 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host:  " ; tput sgr0
    read port
    $xterm -p $port --script afp-brute $ip &

  elif [[ $Brute -eq 2 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host:  " ; tput sgr0
    read port
    $xterm -p $port $ip --script ajp-brute &

  elif [[ $Brute -eq 3 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host:  " ; tput sgr0
    read port
    $xterm -sU --script backorifice-brute $ip --script-args backorifice-brute.ports=$port &

  elif [[ $Brute -eq 4 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 9160 $ip --script=cassandra-brute &

  elif [[ $Brute -eq 5 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=cics-enum -p 23 $ip &

  elif [[ $Brute -eq 6 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=cics-user-enum -p 23 $ip &

  elif [[ $Brute -eq 7 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " What Userdb " ; tput sgr0
    read userdb
    echo -ne $okegreen " What Passdb " ; tput sgr0
    read passdb
    echo -ne $okegreen " What domain " ; tput sgr0
    read domain
    $xterm --script=citrix-brute-xml --script-args=userdb=$userdb,passdb=$passdb,ntdomain=$domain -p 80,443,8080 $ip &

  elif [[ $Brute -eq 8 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 2401 --script cvs-brute $ip &

  elif [[ $Brute -eq 9 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 2401 --script cvs-brute-repository $ip &

  elif [[ $Brute -eq 10 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script domcon-brute -p 2050 $ip &

  elif [[ $Brute -eq 11 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script dpap-brute -p 8770 $ip &

  elif [[ $Brute -eq 12 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 50000 --script drda-brute $ip &

  elif [[ $Brute -eq 13 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host:  " ; tput sgr0
    read port
    $xterm --script ftp-brute -p $port $ip &

  elif [[ $Brute -eq 14 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script http-form-brute -p 80 $ip &

  elif [[ $Brute -eq 15 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p80 --script http-iis-short-name-brute $ip &

  elif [[ $Brute -eq 16 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host:  " ; tput sgr0
    read port
    $xterm --script http-brute -p $port $ip &

  elif [[ $Brute -eq 17 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script http-joomla-brute $ip &

  elif [[ $Brute -eq 18 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script http-proxy-brute -p 8080 $ip &

  elif [[ $Brute -eq 19 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script http-wordpress-brute $ip &

  elif [[ $Brute -eq 20 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sU -p 4569 $ip --script iax2-brute &

  elif [[ $Brute -eq 21 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script informix-brute -p 9088 $ip &

  elif [[ $Brute -eq 22 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sU --script ipmi-brute -p 623 $ip &

  elif [[ $Brute -eq 23 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script irc-brute -p 6667 $ip &

  elif [[ $Brute -eq 24 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script irc-sasl-brute -p 6667 $ip &

  elif [[ $Brute -eq 25 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=iscsi-brute $ip &

  elif [[ $Brute -eq 26 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 389 --script ldap-brute --script-args ldap.base='"cn=users,dc=cqure,dc=net"' $ip &

  elif [[ $Brute -eq 27 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 143,993 --script imap-brute $ip &

  elif [[ $Brute -eq 28 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 11211 --script membase-brute &

  elif [[ $Brute -eq 29 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script mmouse-brute -p 51010 $ip &

  elif [[ $Brute -eq 30 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 27017 $ip --script mongodb-brute &

  elif [[ $Brute -eq 31 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 445 --script ms-sql-brute --script-args mssql.instance-all,userdb=customuser.txt,passdb=custompass.txt $ip &

  elif [[ $Brute -eq 32 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=mysql-brute $ip

  elif [[ $Brute -eq 33 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    nmap --script=mysql-enum $ip &

  elif [[ $Brute -eq 34 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 27017 $ip --script mongodb-brute &

  elif [[ $Brute -eq 35 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script metasploit-msgrpc-brute -p 55553 $ip &

  elif [[ $Brute -eq 36 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script metasploit-xmlrpc-brute -p 55553 $ip &

  elif [[ $Brute -eq 37 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 8728 --script mikrotik-routeros-brute $ip &

  elif [[ $Brute -eq 38 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=nessus-xmlrpc-brute $ip &

  elif [[ $Brute -eq 39 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 12345 --script netbus-brute $ip &

  elif [[ $Brute -eq 40 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script nexpose-brute -p 3780 $ip &

  elif [[ $Brute -eq 41 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=nje-node-brute $ip &

  elif [[ $Brute -eq 42 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=nje-pass-brute --script-args=ohost='POTATO',rhost='CACTUS',sleep=5 -p 175 $ip &

  elif [[ $Brute -eq 43 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 9929 --script nping-brute $ip &

  elif [[ $Brute -eq 44 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script nessus-brute -p 1241 $ip &

  elif [[ $Brute -eq 45 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 9390 --script omp2-brute $ip &

  elif [[ $Brute -eq 46 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=openvas-otp-brute $ip &

  elif [[ $Brute -eq 47 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script oracle-brute -p 1521 --script-args oracle-brute.sid=ORCL $ip &

  elif [[ $Brute -eq 48 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script oracle-brute-stealth -p 1521 --script-args oracle-brute-stealth.sid=ORCL $ip &

  elif [[ $Brute -eq 49 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=oracle-sid-brute -p 1521-1560 $ip &

  elif [[ $Brute -eq 50 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=pcanywhere-brute $ip &

  elif [[ $Brute -eq 51 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 5432 --script pgsql-brute $ip &

  elif [[ $Brute -eq 52 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sV --script=pop3-brute $ip &

  elif [[ $Brute -eq 53 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 6379 $ip --script redis-brute &

  elif [[ $Brute -eq 54 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 512 --script rexec-brute $ip &

  elif [[ $Brute -eq 55 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 513 --script rlogin-brute $ip &

  elif [[ $Brute -eq 56 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 2002 $ip --script rpcap-brute &

  elif [[ $Brute -eq 57 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 873 --script rsync-brute --script-args 'rsync-brute.module=www' $ip &

  elif [[ $Brute -eq 58 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script rtsp-url-brute -p 554 $ip &

  elif [[ $Brute -eq 59 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sU -p 5060 $ip --script=sip-brute &

  elif [[ $Brute -eq 60 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script socks-brute -p 1080 $ip &

  elif [[ $Brute -eq 61 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script svn-brute --script-args svn-brute.repo=/svn/ -p 3690 $ip &

  elif [[ $Brute -eq 62 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script=tso-enum -p 23 $ip &

  elif [[ $Brute -eq 63 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -sU -sS --script smb-brute.nse -p U:137,T:139 &

  elif [[ $Brute -eq 64 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 25 --script smtp-brute $ip &

  elif [[ $Brute -eq 65 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Located Wordlist ? :  " ; tput sgr0
    read wordlist
    $xterm -sU --script snmp-brute $ip [--script-args snmp-brute.communitiesdb=$wordlist ]  &

  elif [[ $Brute -eq 66 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    echo -ne $okegreen " Open Port on Target or Host (23):  " ; tput sgr0
    read port
    $xterm -p $port --script telnet-brute --script-args userdb=myusers.lst,passdb=mypwds.lst,telnet-brute.timeout=8s $ip &

  elif [[ $Brute -eq 67 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script vtam-enum -p 23 $ip &

  elif [[ $Brute -eq 68 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 902 $ip --script vmauthd-brute &

  elif [[ $Brute -eq 69 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm --script vnc-brute -p 5900 $ip &

  elif [[ $Brute -eq 70 ]] ; then

    echo
    echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
    read ip
    $xterm -p 5222 --script xmpp-brute $ip &

  elif [[ $Brute -eq 71 ]] ; then

    nse

  else

    echo ""
    echo -e $okegreen " Incorrect Number"

  fi

  echo -n -e "  Back to Last Menu? ( Yes / No ) :"
  read back

  if [ $back != 'n' ] && \
     [ $back != 'N' ] && \
     [ $back != 'no' ] && \
     [ $back != 'No' ] ; then

    clear
    menu

  elif [ $back != 'y' ] && \
       [ $back != 'Y' ] && \
       [ $back != 'yes' ] && \
       [ $back != 'Yes' ] ; then

    brutense

  else

    clear
    brutense

  fi

}
