#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_brutense()
#
# Description:
#   Starting the Dracnmap Brutense module.
#
# Usage:
#   _init_cli_brutense
#
# Examples:
#   _init_cli_brutense
#

function _init_cli_brutense() {

  local _FUNCTION_ID="_init_cli_brutense"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="nse-brute"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        _init_cmd "$xterm -p $port --script afp-brute $_ip"

        cstate=1
        ;;

      02|2)

        _init_cmd "$xterm -p $_port --script ajp-brute $_ip"

        cstate=1
        ;;

      03|3)

        _init_cmd "$xterm -sU --script backorifice-brute --script-args backorifice-brute.ports=$_port $_ip"

        cstate=1
        ;;

      04|4)

        _init_cmd "$xterm -p 9160 --script=cassandra-brute $_ip"

        cstate=1
        ;;

      05|5)

        _init_cmd "$xterm -p 23 --script=cics-enum $_ip"

        cstate=1
        ;;

      06|6)

        _init_cmd "$xterm -p 23 --script=cics-user-enum $_ip"

        cstate=1
        ;;

      07|7)

        _init_cmd "$xterm -p 80,443,8080 --script=citrix-brute-xml --script-args=userdb=$_userdb,passdb=$_passdb,ntdomain=$_domain $_ip"

        cstate=1
        ;;

      08|8)

        _init_cmd "$xterm -p 2401 --script cvs-brute $_ip"

        cstate=1
        ;;

      09|9)

        _init_cmd "$xterm -p 2401 --script cvs-brute-repository $_ip"

        cstate=1
        ;;

      10)

        _init_cmd "$xterm -p 2050 --script domcon-brute $_ip"

        cstate=1
        ;;

      11)

        _init_cmd "$xterm -p 8770 --script dpap-brute $_ip"

        cstate=1
        ;;

      12)

        _init_cmd "$xterm -p 50000 --script drda-brute $_ip"

        cstate=1
        ;;

      13)

        _init_cmd "$xterm -p $_port --script ftp-brute $_ip"

        cstate=1
        ;;

      14)

        _init_cmd "$xterm -p 80 --script http-form-brute $_ip"

        cstate=1
        ;;

      15)

        _init_cmd "$xterm -p $_port --script http-brute $_ip"

        cstate=1
        ;;

      16)

        _init_cmd "$xterm -p 80 --script http-crossdomainxml --script-args http.domain-lookup=true $_ip"

        cstate=1
        ;;

      17)

        _init_cmd "$xterm -sV --script http-joomla-brute $_ip"

        cstate=1
        ;;

      18)

        _init_cmd "$xterm -p 8080 --script http-proxy-brute $_ip"

        cstate=1
        ;;

      19)

        _init_cmd "$xterm -sV --script http-wordpress-brute $_ip"

        cstate=1
        ;;

      20)

        _init_cmd "$xterm -sU -p 4569 --script iax2-brute $_ip"

        cstate=1
        ;;

      21)

        _init_cmd "$xterm -p 9088 --script informix-brute $_ip"

        cstate=1
        ;;

      22)

        _init_cmd "$xterm -sU -p 623 --script ipmi-brute $_ip"

        cstate=1
        ;;

      23)

        _init_cmd "$xterm -p 6667 --script irc-brute $_ip"

        cstate=1
        ;;

      24)

        _init_cmd "$xterm -p 6667 --script irc-sasl-brute $_ip"

        cstate=1
        ;;

      25)

        _init_cmd "$xterm -sV --script=iscsi-brute $_ip"

        cstate=1
        ;;

      26)

        _init_cmd "$xterm -p 389 --script ldap-brute --script-args ldap.base='"cn=users,dc=cqure,dc=net"' $_ip"

        cstate=1
        ;;

      27)

        _init_cmd "$xterm -p 143,993 --script imap-brute $_ip"

        cstate=1
        ;;

      28)

        _init_cmd "$xterm -p 11211 --script membase-brute $_ip"

        cstate=1
        ;;

      29)

        _init_cmd "$xterm -p 51010 --script mmouse-brute $_ip"

        cstate=1
        ;;

      30)

        _init_cmd "$xterm -p 27017 --script mongodb-brute $_ip"

        cstate=1
        ;;

      31)

        _init_cmd "$xterm -p 445 --script ms-sql-brute --script-args mssql.instance-all,userdb=customuser.txt,passdb=custompass.txt $_ip"

        cstate=1
        ;;

      32)

        _init_cmd "$xterm --script=mysql-brute $_ip"

        cstate=1
        ;;

      33)

        _init_cmd "$xterm --script=mysql-enum $_ip"

        cstate=1
        ;;

      34)

        _init_cmd "$xterm -p 27017 --script mongodb-brute $_ip"

        cstate=1
        ;;

      35)

        _init_cmd "$xterm -p 55553 --script metasploit-msgrpc-brute $_ip"

        cstate=1
        ;;

      36)

        _init_cmd "$xterm -p 55553 --script metasploit-xmlrpc-brute $_ip"

        cstate=1
        ;;

      37)

        _init_cmd "$xterm -p 8728 --script mikrotik-routeros-brute $_ip"

        cstate=1
        ;;

      38)

        _init_cmd "$xterm -sV --script=nessus-xmlrpc-brute $_ip"

        cstate=1
        ;;

      39)

        _init_cmd "$xterm -p 12345 --script netbus-brut $_ip"

        cstate=1
        ;;

      40)

        _init_cmd "$xterm -p 3780 --script nexpose-brute $_ip"

        cstate=1
        ;;

      41)

        _init_cmd "$xterm -sV --script=nje-node-brute $_ip"

        cstate=1
        ;;

      42)

        _init_cmd "$xterm -p 175 --script=nje-pass-brute --script-args=ohost='POTATO',rhost='CACTUS',sleep=5 $_ip"

        cstate=1
        ;;

      43)

        _init_cmd "$xterm -p 9929 --script nping-brute $_ip"

        cstate=1
        ;;

      44)

        _init_cmd "$xterm -p 1241 --script nessus-brute $_ip"

        cstate=1
        ;;

      45)

        _init_cmd "$xterm -p 9390 --script omp2-brute $_ip"

        cstate=1
        ;;

      46)

        _init_cmd "$xterm -sV --script=openvas-otp-brute $_ip"

        cstate=1
        ;;

      47)

        _init_cmd "$xterm -p 1521 --script oracle-brute --script-args oracle-brute.sid=ORCL $_ip"

        cstate=1
        ;;

      48)

        _init_cmd "$xterm -p 1521 --script oracle-brute-stealth --script-args oracle-brute-stealth.sid=ORCL $_ip"

        cstate=1
        ;;

      49)

        _init_cmd "$xterm -p 1521-1560 --script=oracle-sid-brute $_ip"

        cstate=1
        ;;

      50)

        _init_cmd "$xterm --script=pcanywhere-brute $_ip"

        cstate=1
        ;;

      51)

        _init_cmd "$xterm -p 5432 --script pgsql-brute $_ip"

        cstate=1
        ;;

      52)

        _init_cmd "$xterm -sV --script=pop3-brute $_ip"

        cstate=1
        ;;

      53)

        _init_cmd "$xterm -p 6379 --script redis-brute $_ip"

        cstate=1
        ;;

      54)

        _init_cmd "$xterm -p 512 --script rexec-brute $_ip"

        cstate=1
        ;;

      55)

        _init_cmd "$xterm -p 513 --script rlogin-brute $_ip"

        cstate=1
        ;;

      56)

        _init_cmd "$xterm -p 2002 $ip --script rpcap-brute $_ip"

        cstate=1
        ;;

      57)

        _init_cmd "$xterm -p 873 --script rsync-brute --script-args 'rsync-brute.module=www' $_ip"

        cstate=1
        ;;

      58)

        _init_cmd "$xterm -p 554 --script rtsp-url-brute $_ip"

        cstate=1
        ;;

      59)

        _init_cmd "$xterm -sU -p 5060 $ip --script=sip-brute $_ip"

        cstate=1
        ;;

      60)

        _init_cmd "$xterm -p 1080 --script socks-brute $_ip"

        cstate=1
        ;;

      61)

        _init_cmd "$xterm -p 3690 --script svn-brute --script-args svn-brute.repo=/svn/ $_ip"

        cstate=1
        ;;

      62)

        _init_cmd "$xterm -p 23 --script=tso-enum $_ip"

        cstate=1
        ;;

      63)

        _init_cmd "$xterm -sU -sS -p U:137,T:139 --script smb-brute.nse $_ip"

        cstate=1
        ;;

      64)

        _init_cmd "$xterm -p 25 --script smtp-brute $_ip"

        cstate=1
        ;;

      65)

        echo -ne $okegreen "Located Wordlist ?: " ; tput sgr0
        read _wordlist

        _init_cmd "$xterm -sU --script snmp-brute [--script-args snmp-brute.communitiesdb="$_wordlist"] $_ip"

        cstate=1
        ;;

      66)

        _init_cmd "$xterm -p $port --script telnet-brute --script-args userdb=myusers.lst,passdb=mypwds.lst,telnet-brute.timeout=8s $_ip"

        cstate=1
        ;;

      67)

        _init_cmd "$xterm -p 23 --script vtam-enum $_ip"

        cstate=1
        ;;

      68)

        _init_cmd "$xterm -p 902 --script vmauthd-brute $_ip"

        cstate=1
        ;;

      69)

        _init_cmd "$xterm -p 5900 --script vnc-brute $_ip"

        cstate=1
        ;;

      70)

        _init_cmd "$xterm -p 5222 --script xmpp-brute $_ip"

        cstate=1
        ;;

      help)

        _help_
        cstate="0" ;;

      show)

        if [ ${input_array[1]} ] ; then

          case ${input_array[1]} in

            session)

              show_session
              ;;

            *)
              printf "stdout: %s\n" "unknown command" ;;

          esac

        else

          printf "stdout: %s\n" "unknown argument"

        fi
        cstate="0" ;;

      set)

        if [ ${input_array[1]} ] ; then

          case ${input_array[1]} in

            session)

              if [ ${input_array[2]} ] ; then

                set_session "${input_array[2]}"

              else

                printf "stdout: %s\n" "invalid session params"

              fi
              ;;

            *)
              printf "stdout: %s\n" "unknown command" ;;

          esac

        else

          printf "stdout: %s\n" "unknown argument"

        fi
        cstate="0" ;;

      clear)
        menu_brutense
        _init_cli_brutense
        cstate="0" ;;
      back)
        menu_nse
        _init_cli_nse
        cstate="0" ;;
      main)
        menu
        _init_cli
        cstate="0" ;;
      exit)
        _exit_ 0 ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

################################################
# NSE SCRIPT FOR BRUTEFORCE
################################################

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed leading and trailing whitespaces
#   - added smart tabs
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
#   - correcting indentation (transparent code)
function menu_brutense() {

  clear
  echo "";
  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white "    [$okegreen"01"$white]$cyan  afp-brute"
  echo -e $white "    [$okegreen"02"$white]$cyan  ajp-brute"
  echo -e $white "    [$okegreen"03"$white]$cyan  backorifice-brute"
  echo -e $white "    [$okegreen"04"$white]$cyan  cassandra-brute"
  echo -e $white "    [$okegreen"05"$white]$cyan  cics-enum"
  echo -e $white "    [$okegreen"06"$white]$cyan  cics-user-enum"
  echo -e $white "    [$okegreen"07"$white]$cyan  citrix-brute-xml"
  echo -e $white "    [$okegreen"08"$white]$cyan  cvs-brute"
  echo -e $white "    [$okegreen"09"$white]$cyan  cvs-brute-repository"
  echo -e $white "    [$okegreen"10"$white]$cyan  domcon-brute"
  echo -e $white "    [$okegreen"11"$white]$cyan  dpap-enum"
  echo -e $white "    [$okegreen"12"$white]$cyan  drda-brute"
  echo -e $white "    [$okegreen"13"$white]$cyan  ftp-brute"
  echo -e $white "    [$okegreen"14"$white]$cyan  http-from-brute"
  echo -e $white "    [$okegreen"15"$white]$cyan  http-iis-short-name-brute"
  echo -e $white "    [$okegreen"16"$white]$cyan  http-brute"
  echo -e $white "    [$okegreen"17"$white]$cyan  http-joomla-brute"
  echo -e $white "    [$okegreen"18"$white]$cyan  http-proxy-brute"
  echo -e $white "    [$okegreen"19"$white]$cyan  http-wordpress-brute"
  echo -e $white "    [$okegreen"20"$white]$cyan  iax2-brute"
  echo -e $white "    [$okegreen"21"$white]$cyan  informix-brute"
  echo -e $white "    [$okegreen"22"$white]$cyan  ipmi-brute"
  echo -e $white "    [$okegreen"23"$white]$cyan  irc-brute"
  echo -e $white "    [$okegreen"24"$white]$cyan  irc-sasl-brute"
  echo -e $white "    [$okegreen"25"$white]$cyan  iscsi-brute"
  echo -e $white "    [$okegreen"26"$white]$cyan  ldap-brute"
  echo -e $white "    [$okegreen"27"$white]$cyan  imap-brute"
  echo -e $white "    [$okegreen"28"$white]$cyan  membase-brute"
  echo -e $white "    [$okegreen"29"$white]$cyan  mmouse-brute"
  echo -e $white "    [$okegreen"30"$white]$cyan  mongodb-brute"
  echo -e $white "    [$okegreen"31"$white]$cyan  ms-sql-brute"
  echo -e $white "    [$okegreen"32"$white]$cyan  mysql-brute"
  echo -e $white "    [$okegreen"33"$white]$cyan  mysql-enum"
  echo -e $white "    [$okegreen"34"$white]$cyan  mongodb-brute"
  echo -e $white "    [$okegreen"35"$white]$cyan  metasploit-msgrpc-brute"
  echo -e $white "    [$okegreen"36"$white]$cyan  metasploit-xmlrpc-brute"
  echo -e $white "    [$okegreen"37"$white]$cyan  mikrotik-routeros-brute"
  echo -e $white "    [$okegreen"38"$white]$cyan  nessus-xmlrpc-brute"
  echo -e $white "    [$okegreen"39"$white]$cyan  netbus-brute"
  echo -e $white "    [$okegreen"40"$white]$cyan  nexpose-brute"
  echo -e $white "    [$okegreen"41"$white]$cyan  nje-node-brute"
  echo -e $white "    [$okegreen"42"$white]$cyan  nje-pass-brute"
  echo -e $white "    [$okegreen"43"$white]$cyan  nping-brute"
  echo -e $white "    [$okegreen"44"$white]$cyan  nessus-brute"
  echo -e $white "    [$okegreen"45"$white]$cyan  omp2-brute"
  echo -e $white "    [$okegreen"46"$white]$cyan  openvas-otp-brute"
  echo -e $white "    [$okegreen"47"$white]$cyan  oracle-brute"
  echo -e $white "    [$okegreen"48"$white]$cyan  oracle-brute-stealth"
  echo -e $white "    [$okegreen"49"$white]$cyan  oracle-sid-brute"
  echo -e $white "    [$okegreen"50"$white]$cyan  pcanywhere-brute"
  echo -e $white "    [$okegreen"51"$white]$cyan  pgsql-brute"
  echo -e $white "    [$okegreen"52"$white]$cyan  pop3-brute"
  echo -e $white "    [$okegreen"53"$white]$cyan  redis-brute"
  echo -e $white "    [$okegreen"54"$white]$cyan  rexec-brute"
  echo -e $white "    [$okegreen"55"$white]$cyan  rlogin-brute"
  echo -e $white "    [$okegreen"56"$white]$cyan  rpcap-brute"
  echo -e $white "    [$okegreen"57"$white]$cyan  rsync-brute"
  echo -e $white "    [$okegreen"58"$white]$cyan  rtsp-url-brute"
  echo -e $white "    [$okegreen"59"$white]$cyan  sip-brute"
  echo -e $white "    [$okegreen"60"$white]$cyan  socks-brute"
  echo -e $white "    [$okegreen"61"$white]$cyan  svn-brute"
  echo -e $white "    [$okegreen"62"$white]$cyan  tso-enum"
  echo -e $white "    [$okegreen"63"$white]$cyan  smb-brute"
  echo -e $white "    [$okegreen"64"$white]$cyan  smtp-brute"
  echo -e $white "    [$okegreen"65"$white]$cyan  snmp-brute"
  echo -e $white "    [$okegreen"66"$white]$cyan  telnet-brute"
  echo -e $white "    [$okegreen"67"$white]$cyan  vtam-enum"
  echo -e $white "    [$okegreen"68"$white]$cyan  vmauthd-brute"
  echo -e $white "    [$okegreen"69"$white]$cyan  vnc-brute"
  echo -e $white "    [$okegreen"70"$white]$cyan  xmpp-brute"
  echo -e " "

}
