#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_fuzzer()
#
# Description:
#   Starting the Dracnmap Fuzzer module.
#
# Usage:
#   _init_cli_fuzzer
#
# Examples:
#   _init_cli_fuzzer
#

function _init_cli_fuzzer() {

  local _FUNCTION_ID="_init_cli_fuzzer"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="nse-fuzzer"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        $xterm -sU --script dns-fuzz --script-args timelimit=2h $_ip

        cstate=1
        ;;

      02|2)

        $xterm -p 80 --script http-form-fuzzer --script-args 'http-form-fuzzer.targets={1={path=/},2={path=/register.html}}' $_ip

        cstate=1
        ;;

      03|3)

        $xterm -p80 --script=http-phpself-xss $_ip

        cstate=1
        ;;

      clear)
        menu_fuzzer
        cstate="0" ;;
      back)
        menu_nse
        cstate="0" ;;
      main)
        menu
        cstate="0" ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function menu_fuzzer() {

  clear
  echo
  echo

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan File dns-fuzz "
  echo -e $white"    [$okegreen"02"$white]$cyan File http-form-fuzzer  "
  echo -e $white"    [$okegreen"03"$white]$cyan File http-phpself-xss  "
  echo -e " "

}
