#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_nse()
#
# Description:
#   Starting the Dracnmap NSE module.
#
# Usage:
#   _init_cli_nse
#
# Examples:
#   _init_cli_nse
#

function _init_cli_nse() {

  local _FUNCTION_ID="_init_cli_nse"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="nse"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        menu_auth
        _init_cli_auth

        cstate=1
        ;;

      02|2)

        menu_brd
        _init_cli_brd

        cstate=1
        ;;

      03|3)

        menu_brutense
        _init_cli_brutense

        cstate=1
        ;;

      04|4)

        menu_exploit
        _init_cli_exploit

        cstate=1
        ;;

      05|5)

        menu_fuzzer
        _init_cli_fuzzer

        cstate=1
        ;;

      06|6)

        menu_malware
        _init_cli_malware

        cstate=1
        ;;

      07|7)

        menu_vuln
        _init_cli_vuln

        cstate=1
        ;;

      clear)
        menu_nse
        _init_cli_nse
        cstate="0" ;;
      back)
        menu
        _init_cli
        cstate="0" ;;
      main)
        menu
        _init_cli
        cstate="0" ;;
      exit)
        _exit_ 0 ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function menu_nse() {

  clear
  echo -e $okegreen " "
  echo "    )   *           (      (         (   (   (            ";
  echo " ( /( (  \     (     )\ )   )\ )  (   )\ ))\ ))\ )  *   ) ";
  echo " )\()))\))(   )\   (()/(  (()/(  )\ (()/(()/(()/(\  )  /( ";
  echo "((_)\((_)()((((_)(  /(_))  /(_)|((_) /(_))(_))(_))( )(_)) ";
  echo " _((_|_()((_)\ _ )\(_))   (_)) )\___(_))(_))(_)) (_(_())  ";
  echo "| \| |  \/  (_)_\(_) _ \  / __((/ __| _ \_ _| _ \|_   _|  ";
  echo "| .\ | |\/| |/ _ \ |  _/  \__ \| (__|   /| ||  _/  | |    ";
  echo "|_|\_|_|  |_/_/ \_\|_|    |___/ \___|_|_\___|_|    |_|    ";
  echo "                                                          ";
  echo -e $red"  Nmap Script Engine - Advanced Scanning with Nmap Script"

  echo -e $white " "
  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan  auth-category"
  echo -e $white"    [$okegreen"02"$white]$cyan  broadcast-category"
  echo -e $white"    [$okegreen"03"$white]$cyan  brute-category"
  echo -e $white"    [$okegreen"04"$white]$cyan  exploit-category"
  echo -e $white"    [$okegreen"05"$white]$cyan  fuzzer-category"
  echo -e $white"    [$okegreen"06"$white]$cyan  malware-category"
  echo -e $white"    [$okegreen"07"$white]$cyan  vuln-category"
  echo

}
