#!/usr/bin/env bash

################################################
# PING PING BEBEB
################################################

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_pingbebeb()
#
# Description:
#   Starting the Dracnmap Ping module.
#
# Usage:
#   _init_cli_pingbebeb
#
# Examples:
#   _init_cli_pingbebeb
#

function _init_cli_pingbebeb() {

  local _FUNCTION_ID="_init_cli_pingbebeb"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="PING!"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm --script broadcast-ping --script-args broadcast-ping.num_probes=5 $_ip

        fi

        cstate=1
        ;;

      02|2)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm -sP -PS $_ip

        fi

        cstate=1
        ;;

      03|3)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm -sP -PA $_ip

        fi

        cstate=1
        ;;

      04|4)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm -sP -PU $_ip

        fi

        cstate=1
        ;;

      05|5)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm -sP -PE $_ip

        fi

        cstate=1
        ;;

      06|6)

        _get_ip

        if [[ $? -eq 0 ]] ; then

          $xterm -sP -PO --packet-trace $_ip

        fi

        cstate=1
        ;;

      clear)
        menu_pingbebeb
        cstate="0" ;;
      back)
        menu
        cstate="0" ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function menu_pingbebeb() {

  echo -e $okegreen " "
  clear
  echo " "
  echo "                "
  echo ""
  echo "          \|/  "
  echo "         .-*-   "
  echo "        / /|\     "
  echo "       _L_         "
  echo "     ,     .         "
  echo -e $okegreen" (\ /  O O  \ /)  $red ______ _______ _______ _______      __ __      "
  echo -e $okegreen"  \|    _    |/   $red |   __ \_     _|    |  |     __|    |  |  |     "
  echo -e $okegreen"    \  (_)  /     $red |    __/_|   |_|       |    |  |    |__|__|   "
  echo -e $okegreen"    _/.___,\_     $red |___|  |_______|__|____|_______|    |__|__|    "
  echo -e $okegreen"   (_/ alf \_)         "
  echo -e $white " "

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan  BROADCAST PING  "
  echo -e $white"    [$okegreen"02"$white]$cyan  TCP SYN PING SCANS "
  echo -e $white"    [$okegreen"03"$white]$cyan  TCP ACK PING SCANS "
  echo -e $white"    [$okegreen"04"$white]$cyan  UDP PING SCANS "
  echo -e $white"    [$okegreen"05"$white]$cyan  ICMP PING SCANS "
  echo -e $white"    [$okegreen"06"$white]$cyan  IP PROTOCOL PING SCANS "
  echo -e " "

}
