#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_scanoutput()
#
# Description:
#   Starting the Dracnmap Output module.
#
# Usage:
#   _init_cli_scanoutput
#
# Examples:
#   _init_cli_scanoutput
#

function _init_cli_scanoutput() {

  local _FUNCTION_ID="_init_cli_scanoutput"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="WebService"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        echo -ne $cyan"Path Location: /Dracnmap/Output/"
        echo
        echo -ne "Name of Report: "
        read namafile

        $xterm -A -O -oX Output/$namafile.xml $_ip
        firefox Output/$namafile.xml

        cstate=1
        ;;

      02|2)

        echo -ne $cyan"Path Location: /Dracnmap/Output/"
        echo

        echo -ne "Name of Report: "
        read namafile

        $xterm -A -O -oX Output/$namafile.xml $_ip
        xsltproc Output/$namafile.xml -o Output/$namafile.html
        firefox Output/$namafile.html

        cstate=1
        ;;

      03|3)

        echo -ne $cyan"Path Location: /Dracnmap/Output/"
        echo

        echo -ne "Name of Report: "
        read namafile

        $xterm -F -oN Output/$namafile.txt $_ip
        nano Output/$namafile.txt

        cstate=1
        ;;

      04|4)

        echo -ne $cyan"Path Location: /Dracnmap/Output/"
        echo

        echo -ne "Name of Report: "
        read namafile

        $xterm -F -oG Output/$namafile.grep $_ip
        nano Output/$namafile.grep

        cstate=1
        ;;

      clear)
        menu_scanoutput
        cstate="0" ;;
      back)
        menu
        cstate="0" ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

################################################
# OUTPUT FILE
################################################

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
#   - correcting indentation (transparent code)
function menu_scanoutput() {

  echo -e $cyan " "
  clear
  echo "  "
  echo "                "
  echo -e $okegreen"                       /^--^\     /^--^\     /^--^\   $cyan"
  echo -e $okegreen"                       \____/     \____/     \____/   $cyan "
  echo -e $okegreen"                      /      \   /      \   /      \  $cyan"
  echo -e $okegreen"                     |        | |        | |        | $cyan "
  echo -e $okegreen"                      \__  __/   \__  __/   \__  __/  $cyan  MEONG MOEONG "
  echo " |^|^|^|^|^|^|^|^|^|^|^|^\ \^|^|^|^/ /^|^|^|^|^\ \^|^|^|^|^|^|^|^|^|^|^|^| "
  echo " | | | | | | | | | | | | |\ \| | |/ /| | | | | | \ \ | | | | | | | | | | | "
  echo " ########################/ /######\ \###########/ /####################### "
  echo " | | | | | | | | | | | | \/| | | | \/| | | | | |\/ | | | | | | | | | | | | "
  echo " |_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_| "
  echo -e $white " "

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$okegreen  OUTPUT SCAN IN XML FORMATS  "
  echo -e $white"    [$okegreen"02"$white]$okegreen  OUTPUT SCAN IN HTML FORMATS "
  echo -e $white"    [$okegreen"03"$white]$okegreen  OUTPUT SCAN IN NORMAL FORMATS  "
  echo -e $white"    [$okegreen"04"$white]$okegreen  OUTPUT SCAN IN GREPABLE FORMATS "
  echo -e " "

}
