#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_vuln()
#
# Description:
#   Starting the Dracnmap Vuln module.
#
# Usage:
#   _init_cli_vuln
#
# Examples:
#   _init_cli_vuln
#

function _init_cli_vuln() {

  local _FUNCTION_ID="_init_cli_vuln"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="nse-vuln"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        $xterm -sV --script=afp-path-vuln $_ip

        cstate=1
        ;;

      02|2)

        $xterm --script=broadcast-avahi-dos $_ip

        cstate=1
        ;;

      03|3)

        $xterm -sV --script clamav-exec $_ip

        cstate=1
        ;;

      04|4)

        $xterm -p 3632 --script distcc-exec --script-args="distcc-exec.cmd='id'" $_ip

        cstate=1
        ;;

      05|5)

        $xterm -sU -p 53 --script=dns-update --script-args=dns-update.hostname=foo.example.com,dns-update.ip=192.0.2.1 $_ip

        cstate=1
        ;;

      06|6)

        $xterm --script firewall-bypass --script-args firewall-bypass.helper="ftp", firewall-bypass.targetport=22 $_ip

        cstate=1
        ;;

      07|7)

        $xterm -sV --script=ftp-libopie $_ip

        cstate=1
        ;;

      08|8)

        $xterm -p 21 --script ftp-proftpd-backdoor $_ip

        cstate=1
        ;;

      09|9)

        $xterm -p 21 --script ftp-vsftpd-backdoor $_ip

        cstate=1
        ;;

      10)

        $xterm -p $_port --script ftp-vuln-cve2010-4221 $_ip

        cstate=1
        ;;

      11)

        $xterm -p 80 --script http-adobe-coldfusion-apsa1301 --script-args basepath=/cf/adminapi/ $_ip

        cstate=1
        ;;

      12)

        $xterm --script http-debug --script-args http-aspnet-debug.path=/path $_ip

        cstate=1
        ;;

      13)

        $xterm -sV --script http-avaya-ipoffice-users $_ip

        cstate=1
        ;;

      14)

        $xterm -sV --script http-awstatstotals-exec.nse --script-args 'http-awstatstotals-exec.cmd="uname -a", http-awstatstotals-exec.uri=/awstats/index.php' $_ip

        cstate=1
        ;;

      15)

        $xterm -p 80 --script http-axis2-dir-traversal $_ip

        cstate=1
        ;;

      16)

        $xterm -p 80 --script http-crossdomainxml --script-args http.domain-lookup=true $_ip

        cstate=1
        ;;

      17)

        $xterm -p 80 --script http-csrf.nse $_ip

        cstate=1
        ;;

      18)

        $xterm -sV --script http-dlink-backdoor $_ip

        cstate=1
        ;;

      19)

        $xterm -p 80 --script http-dombased-xss.nse $_ip

        cstate=1
        ;;

      20)

        $xterm -sV --script=http-enum $_ip

        cstate=1
        ;;

      21)

        $xterm -p 80 --script http-fileupload-exploiter.nse $_ip

        cstate=1
        ;;

      22)

        $xterm -p 80 --script=http-frontpage-login $_ip

        cstate=1
        ;;

      23)

        echo -en $okegreen " The query for which to return the results " ; tput sgr0
        read _query

        $xterm sV -sC $_ip

        cstate=1
        ;;

      24)

        $xterm -sV http-huawei-hg5xx-vuln $_ip

        cstate=1
        ;;

      25)

        $xterm -p 80,8080 --script http-iis-webdav-vuln $_ip

        cstate=1
        ;;

      26)

        $xterm --script http-internal-ip-disclosure --script-args http-internal-ip-disclosure.path=/path $_ip

        cstate=1
        ;;

      27)

        $xterm -p 80,8080 --script http-litespeed-sourcecode-download --script-args http-litespeed-sourcecode-download.uri=/phpinfo.php $_ip

        cstate=1
        ;;

      28)

        $xterm -p 80 --script http-majordomo2-dir-traversal $_ip

        cstate=1
        ;;

      29)

        $xterm -p 80 --script http-method-tamper --script-args 'http-method-tamper.paths={/protected/db.php,/protected/index.php}' $_ip

        cstate=1
        ;;

      30)

        $xterm --script http-passwd --script-args http-passwd.root=/test/ $_ip

        cstate=1
        ;;

      31)

        $xterm -p 80 --script http-phpmyadmin-dir-traversal $_ip

        cstate=1
        ;;

      32)

        $xterm -sV --script http-self-xss $_ip

        cstate=1
        ;;

      33)

        $xterm -sV -p- --script http-shellshock --script-args uri=/cgi-bin/bin,cmd=ls $_ip

        cstate=1
        ;;

      34)

        $xterm --script http-slowloris-check $_ip

        cstate=1
        ;;

      35)

        $xterm -sV --script=http-sql-injection $_ip

        cstate=1
        ;;

      36)

        $xterm -p 80 --script http-stored-xss.nse $_ip

        cstate=1
        ;;

      37)

        $xterm -p 80 --script http-tplink-dir-traversal.nse --script-args rfile=/etc/topology.conf -d -n -Pn $_ip

        cstate=1
        ;;

      38)

        $xterm --script http-trace -d $_ip

        cstate=1
        ;;

      39)

        $xterm -p 80,443,8222,8333 --script http-vmware-path-vuln $_ip

        cstate=1
        ;;

      40)

        $xterm -p 80 --script http-vuln-cve2006-3392 --script-args http-vuln-cve2006-3392.file=/etc/shadow $_ip

        cstate=1
        ;;

      41)

        $xterm --script=http-vuln-cve2010-0738 --script-args 'http-vuln-cve2010-0738.paths={/path1/,/path2/}' $_ip

        cstate=1
        ;;

      42)

        $xterm --script http-vuln-cve2010-2861 $_ip

        cstate=1
        ;;

      43)

        $xterm -pT:80,443 --script http-vuln-cve2011-3192.nse [--script-args http-vuln-cve2011-3192.hostname=nmap.scanme.org] $_ip

        cstate=1
        ;;

      44)

        $xterm --script http-vuln-cve2011-3368 $_ip

        cstate=1
        ;;

      45)

        $xterm -sV --script http-vuln-cve2012-1823 $_ip

        cstate=1
        ;;

      46)

        $xterm -sV --script http-vuln-cve2013-0156 $_ip

        cstate=1
        ;;

      47)

        $xterm -p80 --script http-rompager-xss $_ip

        cstate=1
        ;;

      48)

        $xterm -p 80 --script http-vuln-cve2013-7091 --script-args http-vuln-cve2013-7091=/ZimBra $_ip

        cstate=1
        ;;

      49)

        $xterm -p 443 --script http-vuln-cve2014-2126 $_ip

        cstate=1
        ;;

      50)

        $xterm -p 443 --script http-vuln-cve2014-2127 $_ip

        cstate=1
        ;;

      51)

        $xterm -p 443 --script http-vuln-cve2014-2128 $_ip

        cstate=1
        ;;

      52)

        $xterm -p 443 --script http-vuln-cve2014-2129 $_ip

        cstate=1
        ;;

      53)

        $xterm --script http-vuln-cve2014-3704 --script-args http-vuln-cve2014-3704.uri="/drupal",http-vuln-cve2014-3704.cleanup=false $_ip

        cstate=1
        ;;

      54)

        $xterm --script http-vuln-cve2014-8877 --script-args http-vuln-cve2014-8877.cmd="whoami",http-vuln-cve2014-8877.uri="/wordpress" $_ip

        cstate=1
        ;;

      55)

        $xterm --script=http-vuln-cve2015-1427 --script-args command='ls' $_ip

        cstate=1
        ;;

      56)

        $xterm -sV --script http-vuln-cve2015-1635 --script-args uri='/anotheruri/' $_ip

        cstate=1
        ;;

      57)

        $xterm -p 7547 --script=http-vuln-misfortune-cookie $_ip

        cstate=1
        ;;

      58)

        $xterm -p 80 -sV --script http-vuln-wnr1000-creds $_ip

        cstate=1
        ;;

      59)

        $xterm -sV --script http-wordpress-users --script-args limit=50 $_ip

        cstate=1
        ;;

      60)

        $xterm -p 623 -sU --script ipmi-cipher-zero $_ip

        cstate=1
        ;;

      61)

        $xterm -p 6667 --script=irc-botnet-channels $_ip

        cstate=1
        ;;

      62)

        $xterm -sV --script=irc-unrealircd-backdoor $_ip

        cstate=1
        ;;

      63)

        $xterm -sV --script mysql-vuln-cve2012-2122 $_ip

        cstate=1
        ;;

      64)

        $xterm -p 12345 --script netbus-auth-bypass $_ip

        cstate=1
        ;;

      65)

        $xterm -p $_port --script qconn-exec --script-args qconn-exec.timeout=60,qconn-exec.bytes=1024,qconn-exec.cmd="uname -a" $_ip

        cstate=1
        ;;

      66)

        $xterm -p 3389 -sV --script=rdp-ms12-020 $_ip

        cstate=1
        ;;

      67)

        $xterm -p 1099 --script=rmi-vuln-classloader $_ip

        cstate=1
        ;;

      68)

        $xterm -p 139 --script=samba-vuln-cve-2012-1182 $_ip

        cstate=1
        ;;

      69)

        $xterm -p T:139 -sU --script smb-vuln-conficker.nse $_ip

        cstate=1
        ;;

      70)

        $xterm -p U:137,T:139 -sU --script smb-vuln-cve2009-3103.nse $_ip

        cstate=1
        ;;

      71)

        $xterm -p U:137,T:139 -sU --script smb-vuln-ms06-025.nse $_ip

        cstate=1
        ;;

      72)

        $xterm -p U:137,T:139 -sU --script smb-vuln-ms07-029.nse $_ip

        cstate=1
        ;;

      73)

        $xterm -p U:137 -sU --script smb-vuln-ms08-067.nse $_ip

        cstate=1
        ;;

      74)

        $xterm -p 445 --script=smb-vuln-ms10-054 --script-args unsafe $_ip

        cstate=1
        ;;

      75)

        $xterm -p 445 --script=smb-vuln-ms10-061 $_ip

        cstate=1
        ;;

      76)

        $xterm -p U:137,T:139 -sU --script smb-vuln-regsvc-dos.nse $_ip

        cstate=1
        ;;

      77)

        $xterm -pT:25,465,587 --script=smtp-vuln-cve2010-4344 --script-args="smtp-vuln-cve2010-4344.exploit" $_ip

        cstate=1
        ;;

      78)

        $xterm -pT:25,465,587 --script=smtp-vuln-cve2011-1720 --script-args='smtp.domain=<domain>' $_ip

        cstate=1
        ;;

      79)

        $xterm -pT:25,465,587 --script=smtp-vuln-cve2011-1764 $_ip

        cstate=1
        ;;

      80)

        $xterm -p 443 --script ssl-ccs-injection $_ip

        cstate=1
        ;;

      81)

        $xterm -p 443 --script ssl-cert-intaddr $_ip

        cstate=1
        ;;

      82)

        $xterm --script ssl-dh-params $_ip

        cstate=1
        ;;

      83)

        $xterm -p 443 --script ssl-heartbleed $_ip

        cstate=1
        ;;

      84)

        $xterm -p 443 --script ssl-known-key $_ip

        cstate=1
        ;;

      85)

        $xterm -p 443 -sV --version-light --script ssl-poodle $_ip

        cstate=1
        ;;

      86)

        $xterm -sV --script=sslv2-drown $_ip

        cstate=1
        ;;

      87)

        $xterm -p 49152 --script supermicro-ipmi-conf $_ip

        cstate=1
        ;;

      88)

        $xterm -sU -p 17185 --script wdb-version $_ip

        cstate=1
        ;;

      clear)
        menu_vuln
        _init_cli_vuln
        cstate="0" ;;
      back)
        menu_nse
        _init_cli_nse
        cstate="0" ;;
      main)
        menu
        _init_cli_nse
        cstate="0" ;;
      exit)
        _exit_ 0 ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function menu_vuln() {

  clear
  echo

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan afp-path-vuln"
  echo -e $white"    [$okegreen"02"$white]$cyan broadcast-avahi-dos"
  echo -e $white"    [$okegreen"03"$white]$cyan clamav-exec"
  echo -e $white"    [$okegreen"04"$white]$cyan distcc-cve2004-2687"
  echo -e $white"    [$okegreen"05"$white]$cyan dns-update"
  echo -e $white"    [$okegreen"06"$white]$cyan firewall-bypass"
  echo -e $white"    [$okegreen"07"$white]$cyan ftp-libopie"
  echo -e $white"    [$okegreen"08"$white]$cyan ftp-proftpd-backdoor"
  echo -e $white"    [$okegreen"09"$white]$cyan ftp-vsftpd-backdoor"
  echo -e $white"    [$okegreen"10"$white]$cyan ftp-vuln-cve2010-4221"
  echo -e $white"    [$okegreen"11"$white]$cyan http-adobe-coldfusion-apsa1301"
  echo -e $white"    [$okegreen"12"$white]$cyan http-aspnet-debug"
  echo -e $white"    [$okegreen"13"$white]$cyan http-avaya-ipoffice-users"
  echo -e $white"    [$okegreen"14"$white]$cyan http-awstatstotals-exec"
  echo -e $white"    [$okegreen"15"$white]$cyan http-axis2-dir-traversal"
  echo -e $white"    [$okegreen"16"$white]$cyan http-cross-domain-policy"
  echo -e $white"    [$okegreen"17"$white]$cyan http-csrf"
  echo -e $white"    [$okegreen"18"$white]$cyan http-dlink-backdoor"
  echo -e $white"    [$okegreen"19"$white]$cyan http-dombased-xss"
  echo -e $white"    [$okegreen"20"$white]$cyan http-enum"
  echo -e $white"    [$okegreen"21"$white]$cyan http-fileupload-exploiter"
  echo -e $white"    [$okegreen"22"$white]$cyan http-frontpage-login"
  echo -e $white"    [$okegreen"23"$white]$cyan http-git"
  echo -e $white"    [$okegreen"24"$white]$cyan http-huawei-hg5xx-vuln"
  echo -e $white"    [$okegreen"25"$white]$cyan http-iis-webdav-vuln"
  echo -e $white"    [$okegreen"26"$white]$cyan http-internal-ip-disclosure"
  echo -e $white"    [$okegreen"27"$white]$cyan http-litespeed-sourcecode-download"
  echo -e $white"    [$okegreen"28"$white]$cyan http-majordomo2-dir-traversal"
  echo -e $white"    [$okegreen"29"$white]$cyan http-method-tamper"
  echo -e $white"    [$okegreen"30"$white]$cyan http-passwd"
  echo -e $white"    [$okegreen"31"$white]$cyan http-phpmyadmin-dir-traversal"
  echo -e $white"    [$okegreen"32"$white]$cyan http-phpself-xss"
  echo -e $white"    [$okegreen"33"$white]$cyan http-shellshock"
  echo -e $white"    [$okegreen"34"$white]$cyan http-slowloris-check"
  echo -e $white"    [$okegreen"35"$white]$cyan http-sql-injection"
  echo -e $white"    [$okegreen"36"$white]$cyan http-stored-xss"
  echo -e $white"    [$okegreen"37"$white]$cyan http-tplink-dir-traversal"
  echo -e $white"    [$okegreen"38"$white]$cyan http-trace"
  echo -e $white"    [$okegreen"39"$white]$cyan http-vmware-path-vuln"
  echo -e $white"    [$okegreen"40"$white]$cyan http-vuln-cve2006-3392"
  echo -e $white"    [$okegreen"41"$white]$cyan http-vuln-cve2010-0738"
  echo -e $white"    [$okegreen"42"$white]$cyan http-vuln-cve2010-2861"
  echo -e $white"    [$okegreen"43"$white]$cyan http-vuln-cve2011-3192"
  echo -e $white"    [$okegreen"44"$white]$cyan http-vuln-cve2011-3368"
  echo -e $white"    [$okegreen"45"$white]$cyan http-vuln-cve2012-1823"
  echo -e $white"    [$okegreen"46"$white]$cyan http-vuln-cve2013-0156"
  echo -e $white"    [$okegreen"47"$white]$cyan http-vuln-cve2013-6786"
  echo -e $white"    [$okegreen"48"$white]$cyan http-vuln-cve2013-7091"
  echo -e $white"    [$okegreen"49"$white]$cyan http-vuln-cve2014-2126"
  echo -e $white"    [$okegreen"50"$white]$cyan http-vuln-cve2014-2127"
  echo -e $white"    [$okegreen"51"$white]$cyan http-vuln-cve2014-2128"
  echo -e $white"    [$okegreen"52"$white]$cyan http-vuln-cve2014-2129"
  echo -e $white"    [$okegreen"53"$white]$cyan http-vuln-cve2014-3704"
  echo -e $white"    [$okegreen"54"$white]$cyan http-vuln-cve2014-8877"
  echo -e $white"    [$okegreen"55"$white]$cyan http-vuln-cve2015-1427"
  echo -e $white"    [$okegreen"56"$white]$cyan http-vuln-cve2015-1635"
  echo -e $white"    [$okegreen"57"$white]$cyan http-vuln-misfortune-cookie"
  echo -e $white"    [$okegreen"58"$white]$cyan http-vuln-wnr1000-creds"
  echo -e $white"    [$okegreen"59"$white]$cyan http-wordpress-users"
  echo -e $white"    [$okegreen"60"$white]$cyan ipmi-cipher-zero"
  echo -e $white"    [$okegreen"61"$white]$cyan irc-botnet-channels"
  echo -e $white"    [$okegreen"62"$white]$cyan irc-unrealircd-backdoor"
  echo -e $white"    [$okegreen"63"$white]$cyan mysql-vuln-cve2012-2122"
  echo -e $white"    [$okegreen"64"$white]$cyan netbus-auth-bypass"
  echo -e $white"    [$okegreen"65"$white]$cyan qconn-exec"
  echo -e $white"    [$okegreen"66"$white]$cyan rdp-vuln-ms12-020"
  echo -e $white"    [$okegreen"67"$white]$cyan rmi-vuln-classloader"
  echo -e $white"    [$okegreen"68"$white]$cyan samba-vuln-cve-2012-1182"
  echo -e $white"    [$okegreen"69"$white]$cyan smb-vuln-conficker"
  echo -e $white"    [$okegreen"70"$white]$cyan smb-vuln-cve2009-3103"
  echo -e $white"    [$okegreen"71"$white]$cyan smb-vuln-ms06-025"
  echo -e $white"    [$okegreen"72"$white]$cyan smb-vuln-ms07-029"
  echo -e $white"    [$okegreen"73"$white]$cyan smb-vuln-ms08-067"
  echo -e $white"    [$okegreen"74"$white]$cyan smb-vuln-ms10-054"
  echo -e $white"    [$okegreen"75"$white]$cyan smb-vuln-ms10-061"
  echo -e $white"    [$okegreen"76"$white]$cyan smb-vuln-regsvc-dos"
  echo -e $white"    [$okegreen"77"$white]$cyan smtp-vuln-cve2010-4344"
  echo -e $white"    [$okegreen"78"$white]$cyan smtp-vuln-cve2011-1720"
  echo -e $white"    [$okegreen"79"$white]$cyan smtp-vuln-cve2011-1764"
  echo -e $white"    [$okegreen"80"$white]$cyan ssl-ccs-injection"
  echo -e $white"    [$okegreen"81"$white]$cyan ssl-cert-intaddr"
  echo -e $white"    [$okegreen"82"$white]$cyan ssl-dh-params"
  echo -e $white"    [$okegreen"83"$white]$cyan ssl-heartbleed"
  echo -e $white"    [$okegreen"84"$white]$cyan ssl-known-key"
  echo -e $white"    [$okegreen"85"$white]$cyan ssl-poodle"
  echo -e $white"    [$okegreen"86"$white]$cyan sslv2-drown"
  echo -e $white"    [$okegreen"87"$white]$cyan supermicro-ipmi-conf"
  echo -e $white"    [$okegreen"88"$white]$cyan wdb-version"
  echo -e " "

}
