#!/usr/bin/env bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _init_cli_zenmapscript()
#
# Description:
#   Starting the Dracnmap Zenmap module.
#
# Usage:
#   _init_cli_zenmapscript
#
# Examples:
#   _init_cli_zenmapscript
#

function _init_cli_zenmapscript() {

  local _FUNCTION_ID="_init_cli_zenmapscript"
  local _STATE=0

  input_array=()

  while [ "${input_array[0]}" != "back" ] ; do

    cstate="1"

    __cli_banner="Headshot"

    printf "\e[1;31m%s\e[m " "${__cli_prompt}${__cli_banner}>" && read -ra input_array

    case ${input_array[0]} in

      01|1)

        _init_cmd "$xterm -T4 -A -v $_ip"

        cstate=1
        ;;

      02|2)

        _init_cmd "$xterm -sS -sU -T4 -A -v $_ip"

        cstate=1
        ;;

      03|3)

        _init_cmd "$xterm -p 1-65535 -T4 -A -v $_ip"

        cstate=1
        ;;

      04|4)

        _init_cmd "$xterm -T4 -F $_ip"

        cstate=1
        ;;

      05|5)

        _init_cmd "$xterm -sV -T4 -O -F --version-light $_ip"

        cstate=1
        ;;

      06|6)

        _init_cmd "$xterm -sN --traceroute $_ip"

        cstate=1
        ;;

      07|7)

        _init_cmd "$xterm -sS -sU -T4 -A -v -PE -PP -PS80,443 -PA3389 -PU40125 -PY -g 53 --script \"default or (discovery and safe)\" $_ip"

        cstate=1
        ;;

      help)

        _help_
        cstate="0" ;;

      show)

        if [ ${input_array[1]} ] ; then

          case ${input_array[1]} in

            session)

              show_session
              ;;

            *)
              printf "stdout: %s\n" "unknown command" ;;

          esac

        else

          printf "stdout: %s\n" "unknown argument"

        fi
        cstate="0" ;;

      set)

        if [ ${input_array[1]} ] ; then

          case ${input_array[1]} in

            session)

              if [ ${input_array[2]} ] ; then

                set_session "${input_array[2]}"

              else

                printf "stdout: %s\n" "invalid session params"

              fi
              ;;

            *)
              printf "stdout: %s\n" "unknown command" ;;

          esac

        else

          printf "stdout: %s\n" "unknown argument"

        fi
        cstate="0" ;;

      clear)

        menu_zenmapscript
        _init_cli_zenmapscript
        cstate="0" ;;

      back)

        menu
        _init_cli
        cstate="0" ;;

      main)

        menu
        _init_cli
        cstate="0" ;;

      nmap)

        _init_cmd "nmap ${input_array[@]:1}"
        cstate="0" ;;

      exit)
        _exit_ 0 ;;
      "")
        echo -en ""
        cstate="0" ;;
      *)

        if [ "$cstate" -eq "1" ] ; then

          printf "stdout: unknown command\n"

        fi

      ;;

    esac

  done

  return $_STATE

}

###############################################
# ZENMAP
###############################################

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
#   - protection against giving an illegal value
function menu_zenmapscript() {

  clear
  clear
  echo ""
  echo -e $okegreen" ===================================================================="
  echo -e $cyan""
  echo "           +--^----------,--------,-----,--------^-, "
  echo -e "           | $red |||||||||   --------      |         O "
  echo -e $cyan"           +---------------------------^----------| "
  echo -e $cyan"            \_,---------,---------,--------------' "
  echo -e "              / $red"XXXXXX"$cyan /'|       /' "
  echo -e "             / $red"XXXXXX"$cyan /   \    /' "
  echo -e "            / $red"XXXXXX"$cyan / _______/ "
  echo -e "           / $red"XXXXXX"$cyan / "
  echo -e "           / $red"XXXXXX"$cyan / "
  echo "           (________(   "
  echo -e "            ------'        $red DOUBLE KILL !! GO GO GO !!  "
  echo ""
  echo -e $okegreen" ====================================================================="
  echo -e $cyan "       Scanning Target with $red'advanced command  ( Zenmap Command )  "
  echo -e $okegreen" ====================================================================="
  echo ""

  echo -e $white"     ID                    DESCRIPTION"
  echo -e $white"    ---------------------------------------------------------"
  echo -e $white"    [$okegreen"01"$white]$cyan  Intense Scan"
  echo -e $white"    [$okegreen"02"$white]$cyan  Intense Scan + UDP "
  echo -e $white"    [$okegreen"03"$white]$cyan  Intense Scan All TCP Ports"
  echo -e $white"    [$okegreen"04"$white]$cyan  Quick Scan"
  echo -e $white"    [$okegreen"05"$white]$cyan  Quick Scan Plus Plus"
  echo -e $white"    [$okegreen"06"$white]$cyan  Quick Traceroute"
  echo -e $white"    [$okegreen"07"$white]$cyan  Comprehensive Scan [BEST]"
  echo -e   " "

}
