#!/usr/bin/env bash

# Author of changes: trimstray (contact@nslab.at, https://github.com/trimstray)
#   - removed blank spaces/tabs
#   - correcting indentation (transparent code)
#   - replaced 'test' to '[[ ]]'
#   - changed comparison operator (-eq)
function vuln () {

  clear
  echo
  echo -e $white" [$okegreen"01"$white]$cyan afp-path-vuln  "
  echo -e $white" [$okegreen"02"$white]$cyan broadcast-avahi-dos "
  echo -e $white" [$okegreen"03"$white]$cyan clamav-exec "
  echo -e $white" [$okegreen"04"$white]$cyan distcc-cve2004-2687 "
  echo -e $white" [$okegreen"05"$white]$cyan dns-update "
  echo -e $white" [$okegreen"06"$white]$cyan firewall-bypass "
  echo -e $white" [$okegreen"07"$white]$cyan ftp-libopie "
  echo -e $white" [$okegreen"08"$white]$cyan ftp-proftpd-backdoor "
  echo -e $white" [$okegreen"09"$white]$cyan ftp-vsftpd-backdoor "
  echo -e $white" [$okegreen"10"$white]$cyan ftp-vuln-cve2010-4221 "
  echo -e $white" [$okegreen"11"$white]$cyan http-adobe-coldfusion-apsa1301 "
  echo -e $white" [$okegreen"12"$white]$cyan http-aspnet-debug "
  echo -e $white" [$okegreen"13"$white]$cyan http-avaya-ipoffice-users "
  echo -e $white" [$okegreen"14"$white]$cyan http-awstatstotals-exec "
  echo -e $white" [$okegreen"15"$white]$cyan http-axis2-dir-traversal "
  echo -e $white" [$okegreen"16"$white]$cyan http-cross-domain-policy "
  echo -e $white" [$okegreen"17"$white]$cyan http-csrf "
  echo -e $white" [$okegreen"18"$white]$cyan http-dlink-backdoor "
  echo -e $white" [$okegreen"19"$white]$cyan http-dombased-xss "
  echo -e $white" [$okegreen"20"$white]$cyan http-enum "
  echo -e $white" [$okegreen"21"$white]$cyan http-fileupload-exploiter "
  echo -e $white" [$okegreen"22"$white]$cyan http-frontpage-login "
  echo -e $white" [$okegreen"23"$white]$cyan http-git "
  echo -e $white" [$okegreen"24"$white]$cyan http-huawei-hg5xx-vuln "
  echo -e $white" [$okegreen"25"$white]$cyan http-iis-webdav-vuln "
  echo -e $white" [$okegreen"26"$white]$cyan http-internal-ip-disclosure "
  echo -e $white" [$okegreen"27"$white]$cyan http-litespeed-sourcecode-download "
  echo -e $white" [$okegreen"28"$white]$cyan http-majordomo2-dir-traversal "
  echo -e $white" [$okegreen"29"$white]$cyan http-method-tamper "
  echo -e $white" [$okegreen"30"$white]$cyan http-passwd "
  echo -e $white" [$okegreen"31"$white]$cyan http-phpmyadmin-dir-traversal "
  echo -e $white" [$okegreen"32"$white]$cyan http-phpself-xss "
  echo -e $white" [$okegreen"33"$white]$cyan http-shellshock "
  echo -e $white" [$okegreen"34"$white]$cyan http-slowloris-check "
  echo -e $white" [$okegreen"35"$white]$cyan http-sql-injection "
  echo -e $white" [$okegreen"36"$white]$cyan http-stored-xss "
  echo -e $white" [$okegreen"37"$white]$cyan http-tplink-dir-traversal "
  echo -e $white" [$okegreen"38"$white]$cyan http-trace "
  echo -e $white" [$okegreen"39"$white]$cyan http-vmware-path-vuln "
  echo -e $white" [$okegreen"40"$white]$cyan http-vuln-cve2006-3392 "
  echo -e $white" [$okegreen"41"$white]$cyan http-vuln-cve2010-0738 "
  echo -e $white" [$okegreen"42"$white]$cyan http-vuln-cve2010-2861 "
  echo -e $white" [$okegreen"43"$white]$cyan http-vuln-cve2011-3192 "
  echo -e $white" [$okegreen"44"$white]$cyan http-vuln-cve2011-3368 "
  echo -e $white" [$okegreen"45"$white]$cyan http-vuln-cve2012-1823 "
  echo -e $white" [$okegreen"46"$white]$cyan http-vuln-cve2013-0156 "
  echo -e $white" [$okegreen"47"$white]$cyan http-vuln-cve2013-6786 "
  echo -e $white" [$okegreen"48"$white]$cyan http-vuln-cve2013-7091 "
  echo -e $white" [$okegreen"49"$white]$cyan http-vuln-cve2014-2126 "
  echo -e $white" [$okegreen"50"$white]$cyan http-vuln-cve2014-2127 "
  echo -e $white" [$okegreen"51"$white]$cyan http-vuln-cve2014-2128 "
  echo -e $white" [$okegreen"52"$white]$cyan http-vuln-cve2014-2129 "
  echo -e $white" [$okegreen"53"$white]$cyan http-vuln-cve2014-3704 "
  echo -e $white" [$okegreen"54"$white]$cyan http-vuln-cve2014-8877 "
  echo -e $white" [$okegreen"55"$white]$cyan http-vuln-cve2015-1427 "
  echo -e $white" [$okegreen"56"$white]$cyan http-vuln-cve2015-1635 "
  echo -e $white" [$okegreen"57"$white]$cyan http-vuln-misfortune-cookie "
  echo -e $white" [$okegreen"58"$white]$cyan http-vuln-wnr1000-creds "
  echo -e $white" [$okegreen"59"$white]$cyan http-wordpress-users "
  echo -e $white" [$okegreen"60"$white]$cyan ipmi-cipher-zero "
  echo -e $white" [$okegreen"61"$white]$cyan irc-botnet-channels "
  echo -e $white" [$okegreen"62"$white]$cyan irc-unrealircd-backdoor "
  echo -e $white" [$okegreen"63"$white]$cyan mysql-vuln-cve2012-2122 "
  echo -e $white" [$okegreen"64"$white]$cyan netbus-auth-bypass "
  echo -e $white" [$okegreen"65"$white]$cyan qconn-exec "
  echo -e $white" [$okegreen"66"$white]$cyan rdp-vuln-ms12-020 "
  echo -e $white" [$okegreen"67"$white]$cyan rmi-vuln-classloader "
  echo -e $white" [$okegreen"68"$white]$cyan samba-vuln-cve-2012-1182 "
  echo -e $white" [$okegreen"69"$white]$cyan smb-vuln-conficker "
  echo -e $white" [$okegreen"70"$white]$cyan smb-vuln-cve2009-3103 "
  echo -e $white" [$okegreen"71"$white]$cyan smb-vuln-ms06-025 "
  echo -e $white" [$okegreen"72"$white]$cyan smb-vuln-ms07-029 "
  echo -e $white" [$okegreen"73"$white]$cyan smb-vuln-ms08-067 "
  echo -e $white" [$okegreen"74"$white]$cyan smb-vuln-ms10-054 "
  echo -e $white" [$okegreen"75"$white]$cyan smb-vuln-ms10-061 "
  echo -e $white" [$okegreen"76"$white]$cyan smb-vuln-regsvc-dos "
  echo -e $white" [$okegreen"77"$white]$cyan smtp-vuln-cve2010-4344 "
  echo -e $white" [$okegreen"78"$white]$cyan smtp-vuln-cve2011-1720 "
  echo -e $white" [$okegreen"79"$white]$cyan smtp-vuln-cve2011-1764 "
  echo -e $white" [$okegreen"80"$white]$cyan ssl-ccs-injection "
  echo -e $white" [$okegreen"81"$white]$cyan ssl-cert-intaddr "
  echo -e $white" [$okegreen"82"$white]$cyan ssl-dh-params "
  echo -e $white" [$okegreen"83"$white]$cyan ssl-heartbleed "
  echo -e $white" [$okegreen"84"$white]$cyan ssl-known-key "
  echo -e $white" [$okegreen"85"$white]$cyan ssl-poodle "
  echo -e $white" [$okegreen"86"$white]$cyan sslv2-drown "
  echo -e $white" [$okegreen"87"$white]$cyan supermicro-ipmi-conf "
  echo -e $white" [$okegreen"88"$white]$cyan wdb-version "
  echo -e $white" [$okegreen"89"$white]$cyan back "
  echo -e " "
  echo -n -e $red'  \033[4mScreetsec@nse-vuln:\033[0m>> '; tput sgr0 #insert your choice
  read vuln

  if [[ $vuln -eq 1 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=afp-path-vuln $ip &

  elif [[ $vuln -eq 2 ]] ; then

  echo
  $xterm --script=broadcast-avahi-dos &

  elif [[ $vuln -eq 3 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script clamav-exec $ip &

  elif [[ $vuln -eq 4 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 3632 $ip --script distcc-exec --script-args="distcc-exec.cmd='id'" &

  elif [[ $vuln -eq 5 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU -p 53 --script=dns-update --script-args=dns-update.hostname=foo.example.com,dns-update.ip=192.0.2.1 $ip &

  elif [[ $vuln -eq 6 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script firewall-bypass --script-args firewall-bypass.helper="ftp", firewall-bypass.targetport=22 $ip &

  elif [[ $vuln -eq 7 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=ftp-libopie $ip &

  elif [[ $vuln -eq 8 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script ftp-proftpd-backdoor -p 21 $ip &

  elif [[ $vuln -eq 9 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script ftp-vsftpd-backdoor -p 21 $ip &

  elif [[ $vuln -eq 10 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  echo -ne $okegreen " What is your Port Target or Host: " ; tput sgr0
  read port
  $xterm --script ftp-vuln-cve2010-4221 -p $port $ip &

  elif [[ $vuln -eq 11 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-adobe-coldfusion-apsa1301 --script-args basepath=/cf/adminapi/ $ip &

  elif [[ $vuln -eq 12 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-debug --script-args http-aspnet-debug.path=/path $ip &

  elif [[ $vuln -eq 13 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-avaya-ipoffice-users $ip &

  elif [[ $vuln -eq 14 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-awstatstotals-exec.nse --script-args 'http-awstatstotals-exec.cmd="uname -a", http-awstatstotals-exec.uri=/awstats/index.php' $ip &

  elif [[ $vuln -eq 15 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-axis2-dir-traversal $ip &

  elif [[ $vuln -eq 16 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-crossdomainxml --script-args http.domain-lookup=true $ip &

  elif [[ $vuln -eq 17 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-csrf.nse $ip &

  elif [[ $vuln -eq 18 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-dlink-backdoor $ip &

  elif [[ $vuln -eq 19 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-dombased-xss.nse $ip &

  elif [[ $vuln -eq 20 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=http-enum $ip &

  elif [[ $vuln -eq 21 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-fileupload-exploiter.nse $ip &

  elif [[ $vuln -eq 22 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm $ip -p 80 --script=http-frontpage-login &

  elif [[ $vuln -eq 23 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm sV -sC $ip &

  elif [[ $vuln -eq 24 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV http-huawei-hg5xx-vuln $ip &

  elif [[ $vuln -eq 25 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-iis-webdav-vuln -p 80,8080 $ip &

  elif [[ $vuln -eq 26 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-internal-ip-disclosure --script-args http-internal-ip-disclosure.path=/path $ip &

  elif [[ $vuln -eq 27 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80,8080 --script http-litespeed-sourcecode-download --script-args http-litespeed-sourcecode-download.uri=/phpinfo.php $ip &

  elif [[ $vuln -eq 28 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-majordomo2-dir-traversal $ip &

  elif [[ $vuln -eq 29 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-method-tamper --script-args 'http-method-tamper.paths={/protected/db.php,/protected/index.php}' $ip &

  elif [[ $vuln -eq 30 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-passwd --script-args http-passwd.root=/test/ $ip &

  elif [[ $vuln -eq 31 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-phpmyadmin-dir-traversal $ip &

  elif [[ $vuln -eq 32 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-self-xss $ip &

  elif [[ $vuln -eq 33 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV -p- --script http-shellshock --script-args uri=/cgi-bin/bin,cmd=ls $ip &

  elif [[ $vuln -eq 34 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-slowloris-check $ip &

  elif [[ $vuln -eq 35 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=http-sql-injection $ip &

  elif [[ $vuln -eq 36 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 80 --script http-stored-xss.nse $ip &

  elif [[ $vuln -eq 37 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-tplink-dir-traversal.nse --script-args rfile=/etc/topology.conf -d -n -Pn $ip &

  elif [[ $vuln -eq 38 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-trace -d $ip &

  elif [[ $vuln -eq 39 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vmware-path-vuln -p80,443,8222,8333 $ip &

  elif [[ $vuln -eq 40 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-vuln-cve2006-3392 --script-args http-vuln-cve2006-3392.file=/etc/shadow $ip &

  elif [[ $vuln -eq 41 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=http-vuln-cve2010-0738 --script-args 'http-vuln-cve2010-0738.paths={/path1/,/path2/}' $ip &

  elif [[ $vuln -eq 42 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vuln-cve2010-2861 $ip &

  elif [[ $vuln -eq 43 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vuln-cve2011-3192.nse [--script-args http-vuln-cve2011-3192.hostname=nmap.scanme.org] -pT:80,443 $ip &

  elif [[ $vuln -eq 44 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vuln-cve2011-3368 $ip &

  elif [[ $vuln -eq 45 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-vuln-cve2012-1823 $ip &

  elif [[ $vuln -eq 46 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-vuln-cve2013-0156 $ip &

  elif [[ $vuln -eq 47 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-rompager-xss $ip &

  elif [[ $vuln -eq 48 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p80 --script http-vuln-cve2013-7091 --script-args http-vuln-cve2013-7091=/ZimBra $ip &

  elif [[ $vuln -eq 49 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script http-vuln-cve2014-2126 $ip &

  elif [[ $vuln -eq 50 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script http-vuln-cve2014-2127 $ip &

  elif [[ $vuln -eq 51 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script http-vuln-cve2014-2128 $ip &

  elif [[ $vuln -eq 52 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script http-vuln-cve2014-2129 $ip &

  elif [[ $vuln -eq 53 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vuln-cve2014-3704 --script-args http-vuln-cve2014-3704.uri="/drupal",http-vuln-cve2014-3704.cleanup=false $ip &

  elif [[ $vuln -eq 54 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script http-vuln-cve2014-8877 --script-args http-vuln-cve2014-8877.cmd="whoami",http-vuln-cve2014-8877.uri="/wordpress" $ip &

  elif [[ $vuln -eq 55 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=http-vuln-cve2015-1427 --script-args command= 'ls' $ip &

  elif [[ $vuln -eq 56 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-vuln-cve2015-1635 --script-args uri='/anotheruri/' $ip &

  elif [[ $vuln -eq 57 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm $ip -p 7547 --script=http-vuln-misfortune-cookie &

  elif [[ $vuln -eq 58 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-vuln-wnr1000-creds $ip -p 80 &

  elif [[ $vuln -eq 59 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script http-wordpress-users --script-args limit=50 $ip &

  elif [[ $vuln -eq 60 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script ipmi-cipher-zero -p 623 $ip &

  elif [[ $vuln -eq 61 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 6667 --script=irc-botnet-channels $ip &

  elif [[ $vuln -eq 62 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=irc-unrealircd-backdoor $ip &

  elif [[ $vuln -eq 63 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script mysql-vuln-cve2012-2122 $ip &

  elif [[ $vuln -eq 64 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 12345 --script netbus-auth-bypass $ip &

  elif [[ $vuln -eq 65 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script qconn-exec --script-args qconn-exec.timeout=60,qconn-exec.bytes=1024,qconn-exec.cmd="uname -a" -p $port $ip &

  elif [[ $vuln -eq 66 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=rdp-ms12-020 -p 3389 $ip &

  elif [[ $vuln -eq 67 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=rmi-vuln-classloader -p 1099 $ip &

  elif [[ $vuln -eq 68 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=samba-vuln-cve-2012-1182 -p 139 $ip &

  elif [[ $vuln -eq 69 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-conficker.nse -p T:139 $ip &

  elif [[ $vuln -eq 70 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-cve2009-3103.nse -p U:137,T:139 $ip &

  elif [[ $vuln -eq 71 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-ms06-025.nse -p U:137,T:139 $ip &

  elif [[ $vuln -eq 72 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-ms07-029.nse -p U:137,T:139 $ip &

  elif [[ $vuln -eq 73 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-ms08-067.nse -p U:137 $ip &

  elif [[ $vuln -eq 74 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 445 $ip --script=smb-vuln-ms10-054 --script-args unsafe &

  elif [[ $vuln -eq 75 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm  -p 445 $ip --script=smb-vuln-ms10-061 &

  elif [[ $vuln -eq 76 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU --script smb-vuln-regsvc-dos.nse -p U:137,T:139 $ip &

  elif [[ $vuln -eq 77 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=smtp-vuln-cve2010-4344 --script-args="smtp-vuln-cve2010-4344.exploit" -pT:25,465,587 $ip &

  elif [[ $vuln -eq 78 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script=smtp-vuln-cve2011-1720 --script-args='smtp.domain=<domain>' -pT:25,465,587 $ip &

  elif [[ $vuln -eq 79 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm  --script=smtp-vuln-cve2011-1764 -pT:25,465,587 $ip &

  elif [[ $vuln -eq 80 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script ssl-ccs-injection $ip &

  elif [[ $vuln -eq 81 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script ssl-cert-intaddr $ip &

  elif [[ $vuln -eq 82 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script ssl-dh-params $ip &

  elif [[ $vuln -eq 83 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p 443 --script ssl-heartbleed $ip &

  elif [[ $vuln -eq 84 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm --script ssl-known-key -p 443 $ip &

  elif [[ $vuln -eq 85 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --version-light --script ssl-poodle -p 443 $ip &

  elif [[ $vuln -eq 86 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sV --script=sslv2-drown $ip &

  elif [[ $vuln -eq 87 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -p49152 --script supermicro-ipmi-conf $ip &

  elif [[ $vuln -eq 88 ]] ; then

  echo
  echo -ne $okegreen " What is your IP Target or Host: " ; tput sgr0
  read ip
  $xterm -sU -p 17185 --script wdb-version $ip &

  elif [[ $vuln -eq 89 ]] ; then

  nse

  else

  echo ""
  echo -e $okegreen " Incorrect Number"

  fi

  echo ""
  echo ""
  echo -n -e $red " Back to Last Menu? ( Yes / No ) :"
  read back

  if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
  then

  clear
  menu

  elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
  then

  vuln

  fi

}
